name: CI

on:
  pull_request:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.x
      - run: yarn --frozen-lockfile
      - run: yarn build:frontend
      - uses: superactions/deploy-branch-action@action
        with:
          directory: ./packages/frontend/build
